language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      - g++
      - cmake

install:
  - sudo apt-get install -yq libncurses5-dev libboost-all-dev

before_script:
  - cmake -Bbuild -H.

script:
  - cmake --build build/ --target all
  - cd build/ && ctest
